import '@/app/ui/global.css';


export const metadata = {
    title: 'cratespro',
    description: 'Generated by Next.js',
}

export default function Layout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
