import '@/app/ui/global.css';
import { HeaderProvider } from './context/CrateContext';

export const metadata = {
    title: 'cratespro',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="cn">
            <body>
                <HeaderProvider>
                    {children}
                </HeaderProvider>
            </body>
        </html>
    )
}
