import '@/app/ui/global.css';
import { HeaderProvider } from '../../../context/CrateContext';
import Header from '@/components/HeaderWithSearch';
export const metadata = {
    title: 'cratespro',
    description: 'Generated by Next.js',
}

export default function layout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="cn">
            <body>
                <HeaderProvider>
                    <Header />
                    {children}
                </HeaderProvider>
            </body>
        </html>
    )
}
