on: [push, pull_request]

name: Base GitHub Action for Check, Test and Lints

jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ./package.json

      - name: Install dependencies
        working-directory: ./
        run: npm install --force

      - name: Run ESLint
        working-directory: ./
        run: npm run lint

      - name: Build Next.js application
        working-directory: ./
        run: npm run build
